"""c020 B6/B7 — period-local OSFP with frozen-checkpoint promotion evidence.

Two c019 defects are corrected here, and they compound.

**Audit #12** — G/C accumulated across learning periods. By LP5, the payoff table held games
played by six different learner policies pooled into one row, so "the current policy beats
historical opponent 0 at 56%" was really "the average of six policies, most of them obsolete, beat
it at 56%". Here `G` and `C` are allocated fresh at the start of every period.

**Audit #13** — promotion evidence was not a clean frozen-checkpoint evaluation. c019 promoted
using the same games it trained on, generated by continuously changing weights. Here a period ends
by FREEZING the exact checkpoint, playing a dedicated evaluation against the historical population
with fixed seeds and seats, and populating the payoff row from THOSE GAMES ONLY.

The distinction matters beyond bookkeeping: promotion is supposed to certify that a specific set
of weights is stronger. Evidence generated by weights that no longer exist certifies nothing.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
import sys
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# registered source values (CONTRACT §6)
P_CURRENT_SELF_PLAY = 0.6
XI_PROMOTION = 0.55
MAX_LP_WITHOUT_ADD = 6
MIN_GAMES_PER_HISTORICAL = 20

TEMPERATURE = 0.25
BETA_UNCERTAINTY = 1.0
EPSILON = 1e-3

OSFP_VERSION = "c020.osfp.v1"


class ImmutableCheckpointCollision(Exception):
    """Raised rather than overwriting a promoted historical checkpoint."""


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


@dataclass
class HistoricalModel:
    """B7: every field the contract requires, with an immutable hash."""

    index: int
    path: str
    sha256: str
    training_step: int
    learning_period: int
    creation_reason: str                 # PERFORMANCE_PROMOTION | FORCE_ADD
    payoff_row: Dict[str, Any] = field(default_factory=dict)
    source_evaluation_ids: List[str] = field(default_factory=list)

    def verify(self) -> bool:
        return os.path.exists(self.path) and sha256_file(self.path) == self.sha256

    def to_json(self) -> Dict[str, Any]:
        return {"index": self.index, "path": self.path, "sha256": self.sha256,
                "training_step": self.training_step, "learning_period": self.learning_period,
                "creation_reason": self.creation_reason, "payoff_row": self.payoff_row,
                "source_evaluation_ids": self.source_evaluation_ids[:64]}


@dataclass
class PeriodLocalPayoff:
    """G and C for ONE learning period. Allocated fresh; never carried forward (B6)."""

    lp: int
    size: int
    G: List[float] = field(default_factory=list)
    C: List[int] = field(default_factory=list)
    frozen_checkpoint_sha: Optional[str] = None
    evaluation_ids: List[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.G:
            self.G = [0.0] * self.size
        if not self.C:
            self.C = [0] * self.size

    def record(self, index: int, result_pm_one: float, eval_id: str,
               checkpoint_sha: str) -> None:
        """Record ONE evaluation game. Every game must cite the SAME frozen checkpoint (B6)."""
        if self.frozen_checkpoint_sha is None:
            self.frozen_checkpoint_sha = checkpoint_sha
        elif checkpoint_sha != self.frozen_checkpoint_sha:
            raise ValueError(
                "payoff row mixes checkpoints: promotion evidence must come from ONE frozen "
                f"checkpoint (got {checkpoint_sha[:12]} after {self.frozen_checkpoint_sha[:12]})")
        if 0 <= index < self.size:
            self.G[index] += float(result_pm_one)
            self.C[index] += 1
            if len(self.evaluation_ids) < 4096:
                self.evaluation_ids.append(eval_id)

    def win_rates(self) -> List[Optional[float]]:
        """WIN RATES on [0,1]. `G/C` is a mean payoff on [-1,1] and must be converted."""
        return [(((self.G[i] / self.C[i]) + 1.0) / 2.0) if self.C[i] else None
                for i in range(self.size)]

    def mean_payoffs(self) -> List[Optional[float]]:
        return [(self.G[i] / self.C[i]) if self.C[i] else None for i in range(self.size)]

    def to_json(self) -> Dict[str, Any]:
        return {"lp": self.lp, "size": self.size, "G": self.G, "C": self.C,
                "win_rates": self.win_rates(), "mean_payoffs": self.mean_payoffs(),
                "frozen_checkpoint_sha256": self.frozen_checkpoint_sha,
                "evaluation_games": sum(self.C),
                "period_local": True,
                "note": "allocated fresh at period start; c019 accumulated across periods "
                        "(C019_AUDIT_FINDINGS #12)"}


def sample_probabilities(G: List[float], C: List[int]) -> List[float]:
    """Payoff-driven mixture: harder and less-sampled opponents are drawn more."""
    n = len(C)
    if n == 0:
        return []
    total_c = float(sum(C))
    w = []
    for i in range(n):
        c_i = float(C[i])
        win = ((G[i] / c_i) + 1.0) / 2.0 if c_i > 0 else 0.5
        hardness = float(np.exp((0.5 - win) / TEMPERATURE))
        uncertainty = float(np.sqrt(np.log(1.0 + total_c) / (1.0 + c_i)))
        w.append(hardness * (1.0 + BETA_UNCERTAINTY * uncertainty) + EPSILON)
    s = sum(w) or 1.0
    return [x / s for x in w]


def decide_promotion(payoff: PeriodLocalPayoff, lps_without_add: int,
                     xi: float = XI_PROMOTION, min_games: int = MIN_GAMES_PER_HISTORICAL,
                     max_lp: int = MAX_LP_WITHOUT_ADD) -> Dict[str, Any]:
    """Promotion from FROZEN-checkpoint evidence only (B6)."""
    if payoff.size == 0:
        return {"add": True, "reason": "FIRST_HISTORICAL",
                "detail": "population is empty; the first checkpoint seeds it"}
    if payoff.frozen_checkpoint_sha is None:
        return {"add": False, "reason": "NO_FROZEN_EVIDENCE",
                "detail": "no evaluation games were recorded against the frozen checkpoint"}
    wr = payoff.win_rates()
    common = {"win_rates": wr, "mean_payoffs": payoff.mean_payoffs(), "xi": xi,
              "frozen_checkpoint_sha256": payoff.frozen_checkpoint_sha,
              "evaluation_games": sum(payoff.C), "G": payoff.G, "C": payoff.C}
    sufficient = all(c >= min_games for c in payoff.C)
    beats_all = sufficient and all(w is not None and w > xi for w in wr)
    if beats_all:
        return {"add": True, "reason": "PERFORMANCE_PROMOTION",
                "sufficiently_sampled": True, **common}
    if lps_without_add >= max_lp:
        return {"add": True, "reason": "FORCE_ADD", "lps_without_add": lps_without_add,
                "max_lp": max_lp,
                "note": "implementation evidence only; carries NO strategic strength claim",
                **common}
    return {"add": False, "reason": "NO_PROMOTION", "sufficiently_sampled": sufficient,
            "lps_without_add": lps_without_add, **common}


class HistoricalPopulation:
    """B7: immutable population plus the payoff-derived mixture."""

    def __init__(self, ckpt_dir: str, rng, p_current: float = P_CURRENT_SELF_PLAY):
        self.dir = ckpt_dir
        os.makedirs(ckpt_dir, exist_ok=True)
        self.rng = rng
        self.p_current = p_current
        self.models: List[HistoricalModel] = []
        # mixture weights derived from the LAST period's payoff row, not a schedule
        self.mixture: List[float] = []
        self.samples: List[Dict[str, Any]] = []

    def add(self, src_path: str, training_step: int, lp: int, reason: str,
            payoff_row: Dict[str, Any], eval_ids: List[str]) -> HistoricalModel:
        idx = len(self.models)
        dst = os.path.join(self.dir, f"historical_{idx:03d}_lp{lp:03d}_v{training_step:06d}.pt")
        if os.path.exists(dst):
            raise ImmutableCheckpointCollision(f"{dst} already exists; history is immutable")
        shutil.copy2(src_path, dst)
        os.chmod(dst, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)   # read-only on disk
        m = HistoricalModel(index=idx, path=dst, sha256=sha256_file(dst),
                            training_step=training_step, learning_period=lp,
                            creation_reason=reason, payoff_row=payoff_row,
                            source_evaluation_ids=eval_ids)
        self.models.append(m)
        return m

    def set_mixture_from_payoff(self, payoff: PeriodLocalPayoff) -> List[float]:
        """B7: the next period's opponent mixture derives from the period-local payoff table."""
        if not self.models:
            self.mixture = []
        elif payoff.size == len(self.models):
            self.mixture = sample_probabilities(payoff.G, payoff.C)
        else:
            g = payoff.G + [0.0] * (len(self.models) - payoff.size)
            c = payoff.C + [0] * (len(self.models) - payoff.size)
            self.mixture = sample_probabilities(g, c)
        return self.mixture

    def sample_opponent(self, lp: int) -> Dict[str, Any]:
        """Per GAME. No schedule, no block number."""
        if not self.models or self.rng.random() < self.p_current:
            rec = {"lp": lp, "kind": "CURRENT_SELF_PLAY", "index": None, "path": None,
                   "p_current": self.p_current}
        else:
            probs = self.mixture or [1.0 / len(self.models)] * len(self.models)
            i = int(self.rng.choice(len(probs), p=probs))
            rec = {"lp": lp, "kind": "HISTORICAL_PAYOFF_SAMPLE", "index": i,
                   "path": self.models[i].path,
                   "sha256": self.models[i].sha256,
                   "probability": round(float(probs[i]), 6),
                   "all_probabilities": [round(float(p), 6) for p in probs],
                   "mixture_source": "period_local_payoff_table"}
        if len(self.samples) < 500_000:
            self.samples.append(rec)
        return rec

    def verify_all(self) -> Dict[str, Any]:
        ok = [m.index for m in self.models if m.verify()]
        bad = [m.index for m in self.models if not m.verify()]
        return {"historical": len(self.models), "verified": len(ok),
                "mutated_or_missing": bad, "all_immutable": not bad,
                "hashes": {m.index: m.sha256 for m in self.models}}

    def to_json(self) -> Dict[str, Any]:
        return {"version": OSFP_VERSION, "size": len(self.models),
                "models": [m.to_json() for m in self.models],
                "mixture": [round(float(x), 6) for x in self.mixture]}
